# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lrs.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lrs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlrs.proto\x12\x0croad_network\"3\n\rRouteRequests\x12\x0e\n\x06routes\x18\x01 \x03(\t\x12\x12\n\noutput_shp\x18\x02 \x01(\t\"\x18\n\x08\x46ilePath\x12\x0c\n\x04path\x18\x01 \x01(\t2U\n\x0bRoadNetwork\x12\x46\n\rDownloadAsSHP\x12\x1b.road_network.RouteRequests\x1a\x16.road_network.FilePath\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lrs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEREQUESTS']._serialized_start=27
  _globals['_ROUTEREQUESTS']._serialized_end=78
  _globals['_FILEPATH']._serialized_start=80
  _globals['_FILEPATH']._serialized_end=104
  _globals['_ROADNETWORK']._serialized_start=106
  _globals['_ROADNETWORK']._serialized_end=191
# @@protoc_insertion_point(module_scope)
