# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bridge_master_pb2 as bridge__master__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bridge_master_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetByID = channel.unary_unary(
                '/bridge_master.BridgeMaster/GetByID',
                request_serializer=bridge__master__pb2.BridgeIdRequests.SerializeToString,
                response_deserializer=bridge__master__pb2.Bridges.FromString,
                _registered_method=True)
        self.GetByName = channel.unary_unary(
                '/bridge_master.BridgeMaster/GetByName',
                request_serializer=bridge__master__pb2.NameRequests.SerializeToString,
                response_deserializer=bridge__master__pb2.Bridges.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/bridge_master.BridgeMaster/Insert',
                request_serializer=bridge__master__pb2.Bridges.SerializeToString,
                response_deserializer=bridge__master__pb2.EditResults.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/bridge_master.BridgeMaster/Update',
                request_serializer=bridge__master__pb2.Bridges.SerializeToString,
                response_deserializer=bridge__master__pb2.EditResults.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/bridge_master.BridgeMaster/Delete',
                request_serializer=bridge__master__pb2.ObjectIdRequests.SerializeToString,
                response_deserializer=bridge__master__pb2.EditResults.FromString,
                _registered_method=True)


class BridgeMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByID,
                    request_deserializer=bridge__master__pb2.BridgeIdRequests.FromString,
                    response_serializer=bridge__master__pb2.Bridges.SerializeToString,
            ),
            'GetByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByName,
                    request_deserializer=bridge__master__pb2.NameRequests.FromString,
                    response_serializer=bridge__master__pb2.Bridges.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=bridge__master__pb2.Bridges.FromString,
                    response_serializer=bridge__master__pb2.EditResults.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=bridge__master__pb2.Bridges.FromString,
                    response_serializer=bridge__master__pb2.EditResults.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=bridge__master__pb2.ObjectIdRequests.FromString,
                    response_serializer=bridge__master__pb2.EditResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bridge_master.BridgeMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bridge_master.BridgeMaster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BridgeMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bridge_master.BridgeMaster/GetByID',
            bridge__master__pb2.BridgeIdRequests.SerializeToString,
            bridge__master__pb2.Bridges.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bridge_master.BridgeMaster/GetByName',
            bridge__master__pb2.NameRequests.SerializeToString,
            bridge__master__pb2.Bridges.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bridge_master.BridgeMaster/Insert',
            bridge__master__pb2.Bridges.SerializeToString,
            bridge__master__pb2.EditResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bridge_master.BridgeMaster/Update',
            bridge__master__pb2.Bridges.SerializeToString,
            bridge__master__pb2.EditResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bridge_master.BridgeMaster/Delete',
            bridge__master__pb2.ObjectIdRequests.SerializeToString,
            bridge__master__pb2.EditResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
